import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ── Audience: regular users of the platform ─────────────────────
  userSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        { type: 'autogenerated', dirName: 'getting-started' }
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        { type: 'autogenerated', dirName: 'concepts' }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        { type: 'autogenerated', dirName: 'guides' }
      ],
    },
    {
      type: 'category',
      label: 'Authorization',
      items: [
        'authorization/overview',
        'authorization/managing-roles',
        'authorization/permission-reference',
      ],
    },
    'cdt-vs-alternatives',
  ],

  // ── Audience: developers building on the platform ───────────────
  developerSidebar: [
    'developer-introduction',
    {
      type: 'category',
      label: 'Concepts',
      items: [
        { type: 'autogenerated', dirName: 'concepts' }
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        { type: 'autogenerated', dirName: 'architecture' }
      ],
    },
    {
      type: 'category',
      label: 'Authorization',
      items: [
        'authorization/authorization_roles_permissions',
      ],
    },
    {
      type: 'category',
      label: 'Hooks',
      items: [
        { type: 'autogenerated', dirName: 'hooks' }
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        { type: 'autogenerated', dirName: 'components' }
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      items: [
        { type: 'autogenerated', dirName: 'plugins' }
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        { type: 'autogenerated', dirName: 'contributing' }
      ],
    },
  ],

  // ── Audience: people deploying the platform ─────────────────────
  deploymentSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        { type: 'autogenerated', dirName: 'getting-started' }
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        { type: 'autogenerated', dirName: 'architecture' }
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        { type: 'autogenerated', dirName: 'deployment' }
      ],
    },
    {
      type: 'category',
      label: 'Authorization',
      items: [
        'authorization/overview',
        'authorization/managing-roles',
        'authorization/permission-reference',
      ],
    },
    'changelog',
  ],
};

export default sidebars;
