import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  baseSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        { type: 'autogenerated', dirName: 'getting-started' }
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        { type: 'autogenerated', dirName: 'concepts' }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        { type: 'autogenerated', dirName: 'guides' }
      ],
    },
    {
      type: 'category',
      label: 'Authorization',
      items: [
        { type: 'autogenerated', dirName: 'authorization' }
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        { type: 'autogenerated', dirName: 'architecture' }
      ],
    },
    {
      type: 'category',
      label: 'Hooks',
      items: [
        { type: 'autogenerated', dirName: 'hooks' }
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'autogenerated', dirName: 'api' }
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        { type: 'autogenerated', dirName: 'components' }
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Data Models',
    //   items: [
    //     {type: 'autogenerated', dirName: 'data-model'}
    //   ],
    // },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        { type: 'autogenerated', dirName: 'deployment' }
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      items: [
        { type: 'autogenerated', dirName: 'plugins' }
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        { type: 'autogenerated', dirName: 'contributing' }
      ],
    },
    // Templates category omitted — overview-template.mdx contains
    // placeholder links that break the build. Keep the file for
    // internal reference but don't expose it in the sidebar.
  ]
};

export default sidebars;
